# Site settings
title: Hazel's Blog
email: hairongliu97@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my Blog, welcome!
baseurl: "/Hazel's Blog" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000/Hazel's Blog" # the base hostname & protocol for your site
twitter_username: ...
github_username:  ...

# Build settings
markdown: kramdown
