# Site settings
title: My Blog
email: hairongliu97@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my Blog, welcome!
baseurl: "/HazelBlog" # the subpath of your site, e.g. /blog/
url: "https://hazel-new.github.io/HazelBlog/" # the base hostname & protocol for your site
twitter_username: ...
github_username:  ...

# Build settings
markdown: kramdown

# Add comments
intensedebate_comments: true